package main.java;// Generated by Selenium IDE
import org.junit.jupiter.api.Test;



import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class AaaaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  public void tearDown() {
    driver.quit();
  }
  @Test
  public void aaaa() {
  }

    public static class BankOfAmericaLocater {
        public static void main(String[] args) {
            System.setProperty("webdriver.chrome.driver","C:\\Users\\hacia\\IdeaProjects\\NA_AutoBoot\\chromedriver.exe");
            WebDriver chromeDriver= new ChromeDriver();
            chromeDriver.manage().window().maximize();
            chromeDriver.get("https://www.bankofamerica.com");
            chromeDriver.findElement(By.id("navChecking")).click();

        }
    }
}
